---
ispmail_dovecot_auth_mechanisms: plain login
ispmail_dovecot_database_password: "{{ lookup('password',
  'credentials/dovecot_database_password length=15') }}"
ispmail_dovecot_databases:
  - name: local
    address: /var/run/postgresql
ispmail_debug: false
ispmail_dovecot_replication_peer:

ispmail_dovecot_doveadm_port: 12345
ispmail_dovecot_doveadm_secret: "{{ lookup('password',
  'credentials/dovecot_doveadm_password length=15') }}"
