---
ispmail_pgadmin_ip_range: '0.0.0.0/0'
ispmail_postfix_smtpd_ratelimit: 5000
ispmail_postfix_smtpd_countlimit: 5000

ispmail_mailserver_password: 'TestDatabasePassword'
ispmail_postfix_database_password: 'TestDatabasePassword'
ispmail_dovecot_database_password: 'TestDatabasePassword'

ispmail_public_certificate_directory: /etc/letsencrypt/live/domain
ispmail_public_certificate_location: /etc/letsencrypt/live/domain/fullchain.pem
ispmail_public_certificate_keyfile: /etc/letsencrypt/live/domain/privkey.pem

ispmail_dovecot_disable_auth_penalty: true
