---
- name: Create cert directory
  file:
    path: "{{ ispmail_certificate_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Ensure pip and setuptools are installed
  apt:
    name:
      - python-pip
      - python-setuptools
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3

- name: Ensure python OpenSSL dependencies are installed
  pip:
    name: pyOpenSSL
    state: present
  register: pip_result
  until: pip_result is succeeded
  retries: 3

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ ispmail_certificate_keyfile }}"
    state: present
    mode: 0640
    group: root
    owner: root

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ ispmail_certificate_signing_request }}"
    privatekey_path: "{{ ispmail_certificate_keyfile }}"
    common_name: "{{ ispmail_certificate_domains | join(',') }}"
    country_name: "{{ ispmail_certificate_country }}"
    state_or_province_name: "{{ ispmail_certificate_state }}"
    locality_name: "{{ ispmail_certificate_city }}"
    organization_name: "{{ ispmail_certificate_organisation }}"
    organizational_unit_name: "{{ ispmail_certificate_orgunit }}"
    email_address: "{{ ispmail_certificate_email }}"
    digest: sha512
    state: present

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ispmail_certificate_location }}"
    privatekey_path: "{{ ispmail_certificate_keyfile }}"
    csr_path: "{{ ispmail_certificate_signing_request }}"
    valid_in: "{{ ispmail_certificate_days_valid * 86400 }}"
    provider: selfsigned
    selfsigned_digest: sha512
    state: present

- name: Import PKI tasks
  import_tasks: pki.yml
  become: true

- name: Import internal certs tasks
  import_tasks: internal-certs.yml
