---
- name: Install dovecot packages
  apt:
    name:
      - dovecot-pgsql
      - dovecot-pop3d
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-managesieved
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3

- name: Create the vmail group
  group:
    name: vmail
    gid: 5000

- name: Create the vmail user
  user:
    name: vmail
    uid: 5000
    group: vmail
    home: /var/vmail

- name: Create mailbox directory
  file:
    path: /var/vmail
    state: directory
    owner: vmail
    group: vmail

- name: Grant user dovecot read permission on the private key
  acl:
    path: "{{ certificate_keyfile }}"
    entity: dovecot
    etype: user
    permissions: r
    state: present

- name: Define login trusted networks
  lineinfile:
    dest: /etc/dovecot/dovecot.conf
    regexp: '^(#)?login_trusted_networks ='
    line: 'login_trusted_networks = {{ ispmail_dovecot_login_trusted_networks }}'
    backrefs: true
  notify: restart dovecot

- name: Allow LOGIN authentication method for Outlook clients
  lineinfile:
    dest: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^auth_mechanisms ='
    line: 'auth_mechanisms = {{ ispmail_dovecot_auth_mechanisms }}'
    backrefs: true
  notify: restart dovecot

- name: Disable system authentication
  lineinfile:
    dest: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^!include auth-system.conf.ext'
    line: '#!include auth-system.conf.ext'
    backrefs: true
  notify: restart dovecot

- name: Enable SQL-based authentication
  lineinfile:
    dest: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^\#!include auth-sql.conf.ext'
    line: '!include auth-sql.conf.ext'
    backrefs: true
  notify: restart dovecot

- name: Copy dynamic configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  notify: restart dovecot
  loop:
    - 10-master.conf
    - 10-mail.conf
    - 10-ssl.conf
    - 20-imap.conf
    - 20-pop3.conf
    - auth-sql.conf.ext

- name: Copy static configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  notify: restart dovecot
  loop:
    - 15-mailboxes.conf
    - 20-lmtp.conf
    - 90-sieve.conf

- name: Copy replication conf (if a peer is defined)
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  loop:
    - 30-replication.conf
    - 90-plugin.conf
  when: ispmail_dovecot_replication_peer is defined
  notify: restart dovecot

- name: Remove replication conf (if no peer is defined)
  file:
    path: "/etc/dovecot/conf.d/{{ item }}"
    state: absent
  loop:
    - 30-replication.conf
    - 90-plugin.conf
  when: ispmail_dovecot_replication_peer is not defined

- name: Enable dovecot debug mode
  ini_file:
    path: /etc/dovecot/conf.d/10-logging.conf
    section:
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - option: debug_log_path
      value: /var/log/mail.debug
    - option: auth_verbose
      value: "yes"
    - option: auth_debug
      value: "yes"
    - option: mail_debug
      value: "yes"
  when: ispmail_debug

- name: Generate SQL access configuration for database (<database>-sql.conf)
  template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/{{ item.name }}-sql.conf
    owner: root
  loop: "{{ ispmail_dovecot_databases }}"
  notify: restart dovecot

- name: Fix ownership and mode of dovecot.conf
  file:
    path: /etc/dovecot/dovecot.conf
    group: vmail
    mode: 0644
  notify: restart dovecot

- name: Fix ownership and mode of dovecot-sql.conf.ext
  file:
    path: /etc/dovecot/dovecot-sql.conf.ext
    owner: root
    group: root
    mode: 0640
  notify: restart dovecot

- name: Create directory for global sieve-after scripts
  file:
    path: /etc/dovecot/sieve-after
    state: directory

- name: Create global sieve-after script to send spam to its mail folder
  copy:
    src: spam-to-folder.sieve
    dest: /etc/dovecot/sieve-after/spam-to-folder.sieve
  notify: recompile sieve script
